[ru]
  title = "LeKovr"
  languageName = "русский"
  weight = 1
  contentdir = "content/ru"
  logoText = "Алексей Коврижкин"

[en]
  title = "LeKovr"
  languageName = "english (draft)"
  weight = 2
  contentdir = "content/en"
  logoText = "Aleksei Kovrizhkin"

